export default {
  // screen: "#f7f7f7",
  // card: "#ffffff",
  // buttonColor: "#e8f0fc",
  // buttonText: "#2b64e3",
  // iconColor: "#2b64e3",
  // notSelected: "#777f89",
  screen: "#f7f7f7",
  card: "#ffffff",
  primary: "#1caeff",
  verylightgrey: "#f8fafb",
  lightgrey: "#f8f4f4",
  grey: "#eff1f6",
  darkgrey: "#e2e4e9",
  verydarkgrey: "gray",
  white: "#ffffff",
  blue: "cornflowerblue",
  lightblue: "deepskyblue",
  beige: "cornsilk",
  lightbeige: "ivory",
  gold: "darkgoldenrod",
  cyan: "cyan",
  borderColor: "mistyrose",
};
